services:
  gateway:
    build: 
      dockerfile: docker/Dockerfile.gateway
      context: .
    image: gateway-server
    ports:
      - "3000:3000"
    depends_on:
      - aws_sqs
  processor:
    build: 
      dockerfile: docker/Dockerfile.processor
      context: .
    image: processor-server
    depends_on:
      - aws_sqs
  aws_sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325