FROM node

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.build.json ./

COPY packages/ ./packages/
COPY services/email-processor ./services/email-processor

RUN npm i -g yarn --force
RUN yarn install

RUN yarn workspace @email-service/commons build
RUN yarn workspace email-processor build

CMD [ "yarn", "workspace", "email-processor", "start" ]