FROM node

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

COPY packages/ ./packages/
COPY db-migrations/ ./db-migrations/
COPY .sequelizerc ./

RUN npm i -g yarn --force
RUN yarn install

CMD ["yarn", "run", "sqlz:migrate"]